//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructure.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(CalzadoMetaData))]

    public partial class Calzado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Calzado()
        {
            this.CalzadoxSucursal = new HashSet<CalzadoxSucursal>();
            this.GestionDetalle = new HashSet<GestionDetalle>();
            this.Proveedor = new HashSet<Proveedor>();
        }
    
        public int Id { get; set; }
        public string NombreMarca { get; set; }
        public string IdGenero { get; set; }
        public Nullable<int> IdTalla { get; set; }
        public Nullable<decimal> PrecioProv { get; set; }
        public Nullable<decimal> PrecioVent { get; set; }
        public Nullable<int> CantMin { get; set; }
        public Nullable<int> CantMax { get; set; }
        public Nullable<int> CantTotal { get; set; }
        public byte[] Foto { get; set; }
        public string Descripcion { get; set; }
    
        public virtual TipoGenero TipoGenero { get; set; }
        public virtual Tallas Tallas { get; set; }
        public virtual TipoMarca TipoMarca { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CalzadoxSucursal> CalzadoxSucursal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GestionDetalle> GestionDetalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Proveedor> Proveedor { get; set; }
    }
}
